# --------------------------------------------------------------------
# Setup file for kodi_panel using 480x320 resolution
#
#   For documentation regarding TOML (Tom's Obvious Minimal Language),
#   see references at https://toml.io/en/
#
# --------------------------------------------------------------------

# Specify the Kodi instance to query.  Use localhost if running on
# the same box as Kodi, otherwise specify a resolvable machine name or
# IP address.
BASE_URL = "http://localhost:8080"

# --------------------------------------------------------------------
#
# GPIO setup, display options
#

# Specify the size of the display in pixels.  These values get stored
# into a tuple within kodi_panel and MUST match how the display (or
# framebuffer) is configured.
DISPLAY_WIDTH  = 480 
DISPLAY_HEIGHT = 320 

# GPIO assignment for screen's touch interrupt (T_IRQ), using RPi.GPIO
# numbering.
#
# Assuming your display has a touchscreen with an active-low
# interrupt, find a pin that's unused by luma.  The touchscreen chip
# in my display has its own internal pullup resistor, so no GPIO
# pullup is needed.
#
# I found the following pins to work on the two SBCs.
#
#   Odroid C4:  GPIO19 (physical Pin 35)
#   RPi 3:      GPIO16 (physical Pin 36)
#
# Pin choices are fixed if using the header on the Waveshare displays
# to connect directly to GPIO pins:
#
#   Waveshare 3.5" LCD (B):  GPIO17 (physical pin 11)
#   Waveshare 4" HDMI (H):   GPIO25 (physical pin 22)
#
USE_TOUCH = true   # Set false to disable interrupt use
TOUCH_INT = 17

# The USE_BACKLIGHT boolean controls whether calls are made to
# luma.lcd at all to change backlight state.  Users with OLED displays
# (or using luma.core's linux_framebuffer) should set it to false.
#
# This variable should likely be set false if using the PWM control
# through sysfs files (as presently implemented in kodi_panel_fb.py).
# Note that the framebuffer version (kodi_panel_fb.py) may ignore or
# override this setting, in favor of the group below.
#
USE_BACKLIGHT = true

# See example_setup_800x480.toml for possible hardware PWM
# settings.


# --------------------------------------------------------------------
#
# Display rendering
#

# Paths to default thumbnails.  These do NOT get resized, so they
# should be created at the desired size.
KODI_THUMB      = "images/kodi_thumb.jpg"     # Kodi icon
DEFAULT_THUMB   = "images/music_icon.png"     # standard music file w/o artwork
DEFAULT_AIRPLAY = "images/airplay_thumb.png"  # Airplay file w/o artwork


# Audio Layout Names
#
#   Specify the names of layouts that are available when playing an
#   audio file.  The strings used must correspond to those used within
#   the ALAYOUT dictionary defined below.
#
ALAYOUT_NAMES = [
	"A_DEFAULT",     # small artwork, elapsed time, track info
	"A_FULLSCREEN",  # fullscreen cover only
	"A_FULL_PROG"    # fullscreen cover with vertical progress bar
]

# Initial mode upon startup
ALAYOUT_INITIAL = "A_DEFAULT"


# Colors
#
#   Specify color names to use further below.  To know whether this
#   dictionary needs to be consulted, all names MUST begin with
#   "color_".  Color references without those initial characters just
#   get passed through, without a lookup in this dictionary.
#
#   The two color_progbg and color_progfg colors MUST be defined.
#
[COLORS]
 color_progbg = '#424242'    # progress bar background (used 'dimgrey' for a while)
 color_progfg = '#00FF78'    # progress bar foreground / active portion
 color_7S     = '#00FF78'    # 7-Segment color (used 'SpringGreen' for a while) 
 color_artist = 'yellow'     # artist name


# Font list
#
#   These entries create an array that kodi_panel processes at startup
#   time, pulling the fonts into Pillow.  The font name that is
#   assigned must match those that get used further below in the
#   layouts.
#
#   A "font_main" MUST be defined and successfully loaded.
#

# Standard fonts
[[fonts]]
  name = "font_main"
  path = "fonts/Roboto-Medium.ttf"
  size = 22
  encoding = 'unic'

[[fonts]]
  name = "font_bold"
  path = "fonts/RobotoCondensed-Regular.ttf"
  size = 28
  encoding = 'unic'

[[fonts]]
  name = "font_sm"
  path = "fonts/Roboto-Medium.ttf"
  size = 18
  encoding = 'unic'  

[[fonts]]
  name = "font_tiny"
  path = "fonts/Roboto-Medium.ttf"
  size = 16
  encoding = 'unic'  

# 7-segment font used for elapsed time and track number
[[fonts]]
  name = "font7S"
  path = "fonts/DSEG14Classic-Regular.ttf"
  size = 40

[[fonts]]
  name = "font7S_sm"
  path = "fonts/DSEG14Classic-Regular.ttf"
  size = 12


# --------------------------------------------------------------------
# Audio Screen content
#
#   This data structure gets used by audio_screens() to control the
#   layout and contents of any audio information screens.  Content can
#   be omitted from a screen just by commenting it out here, particular
#   for text fields.
#
#   Top-level entries within this A_LAYOUT table MUST have names that
#   correspond to the ALAYOUT_NAMES list specified earlier in this
#   file.
#
#   New top-level content requires corresponding changes to
#   audio_screens().  If a completely new text field is desired, then
#   the JSON-RPC call made in update_display() needs to be updated as
#   well.
#
#   Special treatment exists for the 'codec' and 'artist' text fields.
#
# --------------------------------------------------------------------

#
# Default audio info screen
#

[A_LAYOUT.A_DEFAULT.thumb]   # Artwork
posx = 4
posy = 4
size = 228
# If artwork is smaller than the above size, should it be centered
# where the fullsize artwork would have been placed?
center_sm = 1    

[A_LAYOUT.A_DEFAULT.prog]    # Progress Bar
posx   = 245     # upper-left corner x position
posy   = 7       # upper-left corner y position
height = 8       # pixel height
short_len = 134  # length when elapsed time matches 00:00 (min, seconds)
long_len  = 208  # length when elapsed time matches 00:00:00 (hrs, mins, seconds)

[[A_LAYOUT.A_DEFAULT.fields]]
name = "MusicPlayer.Time"
posx = 245
posy = 25
font = "font7S"
fill = "color_7S"

[[A_LAYOUT.A_DEFAULT.fields]]
name = "MusicPlayer.TrackNumber"
posx = 245
posy = 99
font = "font7S"
fill = "color_7S"
  # Label only appears if the field is present and non-empty
  label = "Track"
  lposx = 245
  lposy = 78
  lfont = "font_tiny"
  lfill = "white"

#
# This group of fields all appear to the right of the cover art
# and track number, in a small font.
#

# The duration NEVER has decending characters, so it can be somewhat
# closer to the next row
[[A_LAYOUT.A_DEFAULT.fields]]
name = "MusicPlayer.Duration"
posx = 335
posy = 78
font = "font_tiny"
fill = "white"

[[A_LAYOUT.A_DEFAULT.fields]]
name = "codec"   # special treatment in audio_screens()
posx = 335
posy = 98
font = "font_tiny"
fill = "white"

[[A_LAYOUT.A_DEFAULT.fields]]
name = "MusicPlayer.Genre"
posx = 335
posy = 118
font = "font_tiny"
fill = "white"
trunc = 1

[[A_LAYOUT.A_DEFAULT.fields]]
name = "MusicPlayer.Year"
posx = 335
posy = 138
font = "font_tiny"
fill = "white"


#
# Finally, the track title, album title, and artist appear below
# the cover art.
#

[[A_LAYOUT.A_DEFAULT.fields]]
name  = "MusicPlayer.Title"
posx  = 4
posy  = 236
font  = "font_bold"
fill  = "white"
trunc = 1

[[A_LAYOUT.A_DEFAULT.fields]]
name  = "MusicPlayer.Album"
posx  = 4
posy  = 271
font  = "font_sm"
fill  = "white"
trunc = 1

[[A_LAYOUT.A_DEFAULT.fields]]
name  = "artist"   # special treatment in audio_screens()
posx  = 4
posy  = 295
font  = "font_sm"
fill  = "color_artist"
trunc = 1


#
# Fullscreen artwork (by itself)
#

[A_LAYOUT.A_FULLSCREEN.thumb]
center = 1
size = 320
center_sm = 1    


#
# Fullscreen artwork with progress bar
#
[A_LAYOUT.A_FULL_PROG.thumb]
center = 1
size = 320
center_sm = 1    

[A_LAYOUT.A_FULL_PROG.prog]
vertical = 1
posx = 468    # upper-left corner x-position
posy = 1      # upper-left corner y-position
len  = 10     # pixel width for a vertical bar
height = 316  # total height for the vertical bar


# --------------------------------------------------------------------
# Status Screen Content
#
#   Similar to audio layout above, but used for the status screen
#   that appears following a screen touch when idle.  The screen
#   gets drawn by status_screen().
#
#   Special treatment exists for several field names
#

[STATUS_LAYOUT.thumb]   # Kodi logo
posx = 5
posy = 5
size = 128

[[STATUS_LAYOUT.fields]]
name = "version"        # special treatment
posx = 145
posy = 8
font = "font_main"
fill = "color_artist"


[[STATUS_LAYOUT.fields]]
name = "summary"        # special treatment
posx = 145
posy = 35
font = "font_main"
fill = "white"

[[STATUS_LAYOUT.fields]]
name = "time_hrmin"     # special treatment
posx = 145
posy = 73
font = "font7S"
fill = "color_7S"
smfont = "font7S_sm"    # used for AM / PM

# The remaining fields all get populated via a special JSON-RPC query
# to Kodi specifically for the status screen.

[[STATUS_LAYOUT.fields]]
name = "System.Date"
posx = 5
posy = 150
font = "font_sm"
fill = "white"

[[STATUS_LAYOUT.fields]]
name = "System.Uptime"
posx = 5
posy = 175
font = "font_sm"
fill = "white"

[[STATUS_LAYOUT.fields]]
name = "System.CPUTemperature"
posx = 5
posy = 200
font = "font_sm"
fill = "white"

